source: .
destination: ./_site
plugins_dir: ./_plugins
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false
  sass_dir: ./css/_partials
exclude:
  - adoc.*
  - Gemfile*
  - config.rb
  - pry-test.rb
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
gems:
  - jekyll-asciidoc
